name: "DBMigrate"

on:
  pull_request:
    branches: [ "staging" ]
    paths:
      - 'src/db-library/**'
  workflow_dispatch:

jobs:
  migrate:
    name: Migrate
    runs-on: "ubuntu-latest"
    timeout-minutes: 360
    concurrency: build-lock-${{ github.repository }}-${{ github.ref }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check Paths
      id: check_paths
      run: |
        # Check if the pull request includes changes to the specific path
        if git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep -E 'src/db-library/' ; then
          echo "Changes to the specified path found. Workflow continues."
          echo "::set-output name=path_changes::true"
        else
          echo "No changes to the specified path found. Workflow exits."
          echo "::set-output name=path_changes::false"
        fi

    - name: Perform Actions Based on Path Changes
      if: steps.check_paths.outputs.path_changes == 'true'
      run: |
        # Your workflow steps to be executed if changes to the specified path are found
        echo "Performing actions for changes to the specified path."
